### ISSUE TITLE
Angular Traversal dependency

### ISSUE THREAD

**Issue by bloodbare** [plone/pastanaga-angular#172]
Is it really necessary to have angular traversal as dependency on pastanaga-angular. Its only used on the button and I don't really understand why.

**Comment by mathilde-pellerin** [comment]
I agree. We should keep only normal button in pastanaga. Button link is quite a special use case we have, we could/should keep it internal.

**Comment by ebrehault** [comment]
true, it would allow us to get ride of angular/router too, so yes, let's do it

**Comment by ebrehault** [comment]
Ok, I remember now why we needed this button-link with explicit `[routerLink]` or `[traverserTo]`.
The purpose is to allow Ctrl+right-click (or right-click + "Open in new tab") to open the corresponding route or traverse link in another tab.
If we just use a regular button where we have a click function doing the traverse or routing programmatically, it does not work. And it does not work either if we put a `[routerLink]` or `[traverserTo]` on a pa-button (because it has to be on an actual `<a>`).

But ok, I guess it is not a major feature.

**Comment by mathilde-pellerin** [comment]
I didn't say that wouldn't be useful for us, just that we should move this component out of pastanaga to our own project if the dependency is not useful for others :)

**Comment by ebrehault** [comment]
sure, totally agreed, I just wanted to explain what feature we are removing here

**Comment by bloodbare** [comment]
Maybe could be a pastanaga-angular-traversal package? jS world jiji

**Comment by ebrehault** [comment]
no way :)
It will go in grange
