### ISSUE TITLE
Rollback to angular 13

### ISSUE THREAD

**Issue by julienCarret** [plone/pastanaga-angular#590]
There was no announcement for the upgrade to Angular 14. This is preventing us from fixing issues without upgrading our application. the pull request to upgrade was opened during 10 minutes...

**Comment by ebrehault** [comment]
@julienCarret oh, sorry for that!

What I usually do I my Angular open source projects is to have an alternative branch to handle the previous Angular version for people who haven't migrated yet.
So here is the branch forked from version 2.50.7: https://github.com/plone/pastanaga-angular/tree/ng13
You can work on that branch until you migrate, you can just use it directly in your project if you want, but if you prefer you can also create new versions (like 2.50.8, 2.50.9, etc.).
The only difference is you will not have a demo page or the automatic tagging on this branch (I can set automatic tagging if you really need it though)

Sounds good?

**Comment by ebrehault** [comment]
Yes right, well as Angular 14 has been released 3 weeks ago (and as Nx seemed to be updated accordingly, which is always an important thing before starting migrating), I though it was safe to upgrade.
That's the approach I have applied since the beginning of the project (unless when I have been facing major technical blockers), so you can probably expect the same for Angular 15.
But, once again, the temporary branch thing is pretty solid (on another project of mine, we kept the `ng9` branch for 2 years, and it went smoothly).
Note: By the way, if you plan to keep the `ng13` branch running for long, I recommend to make PRs soon enough on `master` with your own changes if they happen to be important.
